datasource:
  driver-class-name: "org.postgresql.Driver"
  url: "jdbc:postgresql://postgresql:5430"
  username: "local"
  password: "local"


volume-path:
  # for windows
  persistent-volume-data: "C:\\volume\\local\\pv\\"
  pod-volume-data: "C:\\volume\\local\\pod\\"

  # for mac
#  persistent-volume-data: "/users/<username>/IdeaProjects/volume/local/pv/"
#  pod-volume-data: "/users/<username>/IdeaProjects/volume/local/pod/"
