# 환경별 application.yaml 파일
spring:
  profiles:
    active: local
  # App 종료시
  lifecycle:
    timeout-per-shutdown-phase: 30s  #Graceful Shutdown시 쓰레드가 종료를 기다리는 시간 (default 30s)

# App Port
server:
  port: 8080
  shutdown: graceful  # Graceful Shutdown 활성화 - 쓰레드가 완전히 종료 될때까지 기다림
  #shutdown: immediate  # Graceful Shutdown 비활성화 - 쓰레드를 바로 중지 시키고 App을 종료함

# App 정보
application:
  role: "ALL"
  version: "Api Tester v3.0.0"

# Database 접속 정보 위치 (Secret으로 주입)
postgresql:
  filepath: "/usr/src/myapp/datasource/postgresql-info.yaml"

# Database 접속 정보
datasource:
  driver-class-name:
  url:
  username:
  password:

# Volume 위치
volume-path:
  persistent-volume-data: 
  pod-volume-data:

# Pod 정보 파일 (Pod의 Volume과 env로 주입)
downward:
  volume:
    filepath:
  env:
    pod-name:
    pod-ip:
    node-name:
termination:
  message-path: "/usr/src/myapp/log/termination.message"

# kube-apiserver 정보 (Secret으로 주입)
api-token:
  url: "https://kubernetes.default"
  filepath: